name: Android Release Build

# Workflow that builds release APK and AAB for:
# 1. Snapshot builds: Each time code changes on main branch
# 2. Release builds: When a GitHub release is published (automatically attaches APK and AAB to release)
# This allows developers and testers to easily download the latest release APK.
# AAB (Android App Bundle) is provided for Google Play Store distribution.
#
# See:
# - https://github.com/hossain-khan/trmnl-android-buddy/tree/main/keystore
# - https://github.com/hossain-khan/trmnl-android-buddy/blob/main/app/build.gradle.kts (signing configuration)

on:
  push:
    branches: [ "main" ]
  # This allows manual triggering of the workflow, which results in making Android Release APK build
  # Go to the "Actions" tab in the repository, select this workflow, and click the "Run workflow" button to run it manually.
  workflow_dispatch:
  # This is triggered when a release is published
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload release assets
      actions: read    # Required to read workflow artifacts
      
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Identify build context
        run: |
          echo "🔍 Build context information:"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "🎉 Building for GitHub release: ${{ github.ref_name }}"
          else
            echo "📦 Building snapshot from main branch"
          fi

      - name: Decode keystore from base64
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore/trmnl-android-buddy-release.keystore

      - name: Build Release APK and AAB
        run: ./gradlew assembleRelease bundleRelease --parallel --daemon
        env:
          KEYSTORE_FILE: keystore/trmnl-android-buddy-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Extract version name
        id: version
        run: |
          VERSION_NAME=$(grep -o 'versionName = "[^"]*"' app/build.gradle.kts | cut -d'"' -f2)
          echo "VERSION=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "App version name extracted: $VERSION_NAME"

      - name: Rename APK and AAB
        run: |
          mkdir -p artifact
          cp app/build/outputs/apk/release/app-release.apk artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.apk
          cp app/build/outputs/bundle/release/app-release.aab artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.aab

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: trmnl-android-buddy-apk
          path: artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.apk
          # Use maximum allowed retention period
          # https://github.com/actions/upload-artifact?tab=readme-ov-file#retention-period
          retention-days: 30

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: trmnl-android-buddy-aab
          path: artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.aab
          retention-days: 30

      # If this is running due to a GitHub release, attach the APK and AAB to the release
      - name: Attach APK and AAB to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attaching APK and AAB to GitHub release..."
          
          # Get release information
          RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" | \
            jq -r .id)
          
          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "❌ Could not find release for tag ${{ github.ref_name }}"
            exit 1
          fi
          
          echo "Found release ID: $RELEASE_ID"
          
          # Upload APK to the release
          APK_FILE="artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.apk"
          APK_NAME="trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.apk"
          
          echo "Uploading $APK_NAME to release..."
          
          UPLOAD_RESPONSE=$(curl -s -w "%{http_code}" -o upload_response.json \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$APK_FILE" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$APK_NAME")
          
          HTTP_CODE="${UPLOAD_RESPONSE: -3}"
          
          if [ "$HTTP_CODE" = "201" ]; then
            echo "✅ Successfully attached APK to GitHub release"
            DOWNLOAD_URL=$(jq -r .browser_download_url upload_response.json)
            echo "APK download URL: $DOWNLOAD_URL"
          else
            echo "❌ Failed to upload APK (HTTP $HTTP_CODE)"
            cat upload_response.json
            exit 1
          fi
          
          # Upload AAB to the release
          AAB_FILE="artifact/trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.aab"
          AAB_NAME="trmnl-android-buddy-v${{ steps.version.outputs.VERSION }}.aab"
          
          echo "Uploading $AAB_NAME to release..."
          
          UPLOAD_RESPONSE=$(curl -s -w "%{http_code}" -o upload_response_aab.json \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$AAB_FILE" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$AAB_NAME")
          
          HTTP_CODE="${UPLOAD_RESPONSE: -3}"
          
          if [ "$HTTP_CODE" = "201" ]; then
            echo "✅ Successfully attached AAB to GitHub release"
            DOWNLOAD_URL=$(jq -r .browser_download_url upload_response_aab.json)
            echo "AAB download URL: $DOWNLOAD_URL"
          else
            echo "❌ Failed to upload AAB (HTTP $HTTP_CODE)"
            cat upload_response_aab.json
            exit 1
          fi
